### ISSUE TITLE
encrypt broken with latest update

### ISSUE THREAD

**Issue by shinji257** [eXhumer/pyTinGen#9]
```
shinji@casper:~/TinGen$ python3 TinGen.py --success "Loaded" --encrypt --index-file /var/www/public_html/shop/index.html [FOLDER_ID]
Generating index
Files scanned: 22.7kfile [02:00, 19.9file/s]Adding success message to index
Creating generated index to /var/www/public_html/shop/index.html
Traceback (most recent call last):
  File "TinGen.py", line 66, in <module>
    create_tinfoil_index(generator.index, Path(args.index_file), compression_flag, rsa_pub_key_path=public_key, vm_path=vm_file)
  File "/home/shinji/TinGen/TinGen/utils.py", line 61, in create_tinfoil_index
    if rsa_pub_key_path is not None and rsa_pub_key_path.is_file():
AttributeError: 'str' object has no attribute 'is_file'
Files scanned: 22.7kfile [02:01, 186file/s]
```

If I leave --encrypt off it works but that makes sense since the traceback is suggesting the error happens when it checks rsa_pub_key_path which defaults to public.pem.  Last known good commits were from April 30th.

Verified it.  Commit https://github.com/eXhumer/TinGen/commit/ce6b739a1af319c1eb4e99c6d3c87c2f06e2397c breaks it.

**Comment by shinji257** [comment]
I believe this will take care of it by making the path (when set) a Path object instead of leaving it as a string.

https://github.com/eXhumer/TinGen/pull/10

**Comment by shinji257** [comment]
This got fixed (in your own way) with https://github.com/eXhumer/TinGen/commit/420d9a811c98ac79a6c2c9afa5eb386b2e61a375 so thank you.
